//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luoyi.Web.Survey {
    
    
    public partial class SiteSurvey {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Luoyi.Web.Controls.OtherPages.SUZHYC Master {
            get {
                return ((Luoyi.Web.Controls.OtherPages.SUZHYC)(base.Master));
            }
        }
    }
}
